[tool.poetry]
name = "blog"
version = "0.1.0"
description = ""
authors = ["nico-Zero <zandaxheart955@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.5"
django = "4.2.9"
django-bootstrap-v5 = "^1.0.11"
django-bootstrap = "^0.2.4"
django-ckeditor = "^6.7.0"
gunicorn = "^21.2.0"
pillow = "^10.2.0"
mysql = "^0.0.3"
postgres = "^4.0"
poetry = "^1.7.1"
dj-database-url = "^2.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
